services:
  # Development frontend (Vite / React dev server)
  frontend-dev:
    build:
      context: .
      target: development
    container_name: event-map-frontend-dev
    ports:
      - "5173:5173"   # dev: exposed to host for local dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles: ["dev"]
    networks:
      - app-network
      - proxy-network

  # Production frontend (Nginx serving built static files)
  frontend-prod:
    build:
      context: .
      target: production
    container_name: event-map-frontend-prod
    restart: always
    profiles: ["prod"]
    networks:
      - app-network
      - proxy-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
  # proxy-network is external so host nginx or nginx-proxy container can attach
  proxy-network:
    external: true

# No volumes defined here (add if needed)
