version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles: ["dev"]

  frontend-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    profiles: ["prod"]
